<%
out.println("<!DOCTYPE html>");
out.println("html lang=\"en\">");
out.println("head>");
out.println("meta charset=\"utf-8\">");
out.println("meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("title>Customer Details</title>");
out.println("link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round\">");
out.println("link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">");
out.println("link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">");
out.println("link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">");
out.println("link rel=\"stylesheet\" type=\"text/css\" href=\"./css/customer_details.css\">");
out.println("script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>");
out.println("script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>");
out.println(" ");
out.println(" <body>");
out.println("   <div class=\"container\">");
out.println("       <div class=\"table-wrapper\">");
out.println("           <div class=\"table-title\">");
out.println("               <div class=\"row\">");
out.println("                   <div class=\"col-sm-6\">");
out.println("					<h2>Manage <b>Customers</b></h2>");
out.println("				</div>");
out.println("				<div class=\"col-sm-6\">");
out.println("					<a href=\"#addCustomerModal\" class=\"btn btn-success\" data-toggle=\"modal\"><i class=\"material-icons\">&#xE147;</i> <span>Add New Customer</span></a>");
out.println("					<!-- <a href=\"#deleteCustomerModal\" class=\"btn btn-danger\" data-toggle=\"modal\"><i class=\"material-icons\">&#xE15C;</i> <span>Delete</span></a>						 -->");
out.println("				</div>");
out.println("               </div>");
out.println("           </div>");
out.println("           <table class=\"table table-striped table-hover\">");
out.println("               <thead>");
out.println("                   <tr>");
out.println("					<th>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"selectAll\">");
out.println("							<label for=\"selectAll\"></label>");
out.println("						</span>");
out.println("					</th>");
out.println("                       <th>Name</th>");
out.println("                       <th>Email</th>");
out.println("                       <th>Phone</th>");
out.println("                       <th>Actions</th>");
out.println("                   </tr>");
out.println("               </thead>");
out.println("               <tbody>");
out.println("                   <tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox1\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox1\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>Thomas Hardy</td>");
out.println("                       <td>thomashardy@mail.com</td>");
out.println("                       <td>(171) 555-2222</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editCustomerModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteCustomerModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>");
out.println("                   <tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox2\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox2\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>Dominique Perrier</td>");
out.println("                       <td>dominiqueperrier@mail.com</td>");
out.println("                       <td>(313) 555-5735</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editCustomerModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteCustomerModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>");
out.println("				<tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox3\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox3\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>Maria Anders</td>");
out.println("                       <td>mariaanders@mail.com</td>");
out.println("                       <td>(503) 555-9931</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editCustomerModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteCustomerModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>");
out.println("                   <tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox4\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox4\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>Fran Wilson</td>");
out.println("                       <td>franwilson@mail.com</td>");
out.println("                       <td>(204) 619-5731</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editCustomerModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteCustomerModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>					");
out.println("				<tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox5\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox5\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>Martin Blank</td>");
out.println("                       <td>martinblank@mail.com</td>");
out.println("                       <td>(480) 631-2097</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editCustomerModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteCustomerModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr> ");
out.println("               </tbody>");
out.println("           </table>");
out.println("		<div class=\"clearfix\">");
out.println("               <div class=\"hint-text\">Showing <b>5</b> out of <b>25</b> entries</div>");
out.println("               <ul class=\"pagination\">");
out.println("                   <li class=\"page-item disabled\"><a href=\"#\">Previous</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">1</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">2</a></li>");
out.println("                   <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">3</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">4</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">5</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">Next</a></li>");
out.println("               </ul>");
out.println("           </div>");
out.println("       </div>");
out.println("   </div>");
out.println("<!-- Edit Modal HTML -->");
out.println("<div id=\"addCustomerModal\" class=\"modal fade\">");
out.println("	<div class=\"modal-dialog\">");
out.println("		<div class=\"modal-content\">");
out.println("			<form>");
out.println("				<div class=\"modal-header\">						");
out.println("					<h4 class=\"modal-title\">Add Customer</h4>");
out.println("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>");
out.println("				</div>");
out.println("				<div class=\"modal-body\">					");
out.println("					<div class=\"form-group\">");
out.println("						<label>Name</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>Email</label>");
out.println("						<input type=\"email\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>Phone</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>					");
out.println("				</div>");
out.println("				<div class=\"modal-footer\">");
out.println("					<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" value=\"Cancel\">");
out.println("					<input type=\"submit\" class=\"btn btn-success\" value=\"Add\">");
out.println("				</div>");
out.println("			</form>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("<!-- Edit Modal HTML -->");
out.println("<div id=\"editCustomerModal\" class=\"modal fade\">");
out.println("	<div class=\"modal-dialog\">");
out.println("		<div class=\"modal-content\">");
out.println("			<form>");
out.println("				<div class=\"modal-header\">						");
out.println("					<h4 class=\"modal-title\">Edit Customer</h4>");
out.println("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>");
out.println("				</div>");
out.println("				<div class=\"modal-body\">					");
out.println("					<div class=\"form-group\">");
out.println("						<label>Name</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>Email</label>");
out.println("						<input type=\"email\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>Phone</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>					");
out.println("				</div>");
out.println("				<div class=\"modal-footer\">");
out.println("					<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" value=\"Cancel\">");
out.println("					<input type=\"submit\" class=\"btn btn-info\" value=\"Save\">");
out.println("				</div>");
out.println("			</form>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("<!-- Delete Modal HTML -->");
out.println("<div id=\"deleteCustomerModal\" class=\"modal fade\">");
out.println("	<div class=\"modal-dialog\">");
out.println("		<div class=\"modal-content\">");
out.println("			<form>");
out.println("				<div class=\"modal-header\">						");
out.println("					<h4 class=\"modal-title\">Delete Customer</h4>");
out.println("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>");
out.println("				</div>");
out.println("				<div class=\"modal-body\">					");
out.println("					<p>Are you sure you want to delete these Records?</p>");
out.println("					<p class=\"text-warning\"><small>This action cannot be undone.</small></p>");
out.println("				</div>");
out.println("				<div class=\"modal-footer\">");
out.println("					<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" value=\"Cancel\">");
out.println("					<input type=\"submit\" class=\"btn btn-danger\" value=\"Delete\">");
out.println("				</div>");
out.println("			</form>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("/body>");
out.println("/html>");
%>