<%
out.println("<!DOCTYPE html>");
out.println("html lang=\"en\">");
out.println("head>");
out.println("meta charset=\"utf-8\">");
out.println("meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
out.println("meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
out.println("title>Order Create</title>");
out.println("link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round\">");
out.println("link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">");
out.println("link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">");
out.println("link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">");
out.println("link rel=\"stylesheet\" type=\"text/css\" href=\"./css/order_create.css\">");
out.println("script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>");
out.println("script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>");
out.println(" ");
out.println(" <body>");
out.println("   <div class=\"container\">");
out.println("       <div class=\"table-wrapper\">");
out.println("           <div class=\"table-title\">");
out.println("               <div class=\"row\">");
out.println("                   <div class=\"col-sm-6\">");
out.println("					<h2>Manage <b>Orders</b></h2>");
out.println("				</div>");
out.println("				<div class=\"col-sm-6\">");
out.println("					<a href=\"#addOrderModal\" class=\"btn btn-success\" data-toggle=\"modal\"><i class=\"material-icons\">&#xE147;</i> <span>Create New Order</span></a>");
out.println("					<!-- <a href=\"#deleteOrderModal\" class=\"btn btn-danger\" data-toggle=\"modal\"><i class=\"material-icons\">&#xE15C;</i> <span>Delete</span></a>						 -->");
out.println("				</div>");
out.println("               </div>");
out.println("           </div>");
out.println("           <table class=\"table table-striped table-hover\">");
out.println("               <thead>");
out.println("                   <tr>");
out.println("					<th>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"selectAll\">");
out.println("							<label for=\"selectAll\"></label>");
out.println("						</span>");
out.println("					</th>");
out.println("                       <th>Order ID</th>");
out.println("                       <th>Employee</th>");
out.println("                       <th>Date</th>");
out.println("                       <th>Type</th>");
out.println("                       <th>From Address</th>");
out.println("                       <th>From Pincode</th>");
out.println("                       <th>To Address</th>");
out.println("                       <th>To Pincode</th>");
out.println("                       <th>Customer</th>");
out.println("                   </tr>");
out.println("               </thead>");
out.println("               <tbody>");
out.println("                   <tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox1\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox1\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("					<td>1</td>");
out.println("					<td>Employee 1</td>");
out.println("					<td>27-Oct-2022</td>");
out.println("					<td>Type 1</td>");
out.println("					<td>From Addr 1</td>");
out.println("					<td>12345</td>");
out.println("					<td>To Addr 1</td>");
out.println("					<td>67890</td>");
out.println("					<td>Customer 1</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editOrderModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteOrderModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>");
out.println("                   <tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox2\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox2\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>2</td>");
out.println("					<td>Employee 2</td>");
out.println("					<td>27-Oct-2022</td>");
out.println("					<td>Type 2</td>");
out.println("					<td>From Addr 2</td>");
out.println("					<td>12345</td>");
out.println("					<td>To Addr 2</td>");
out.println("					<td>67890</td>");
out.println("					<td>Customer 2</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editOrderModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteOrderModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>");
out.println("				<tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox3\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox3\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>3</td>");
out.println("					<td>Employee 3</td>");
out.println("					<td>27-Oct-2022</td>");
out.println("					<td>Type 3</td>");
out.println("					<td>From Addr 3</td>");
out.println("					<td>12345</td>");
out.println("					<td>To Addr 3</td>");
out.println("					<td>67890</td>");
out.println("					<td>Customer 3</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editOrderModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteOrderModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>");
out.println("                   <tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox4\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox4\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>4</td>");
out.println("					<td>Employee 4</td>");
out.println("					<td>27-Oct-2022</td>");
out.println("					<td>Type 4</td>");
out.println("					<td>From Addr 4</td>");
out.println("					<td>12345</td>");
out.println("					<td>To Addr 4</td>");
out.println("					<td>67890</td>");
out.println("					<td>Customer 4</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editOrderModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteOrderModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr>					");
out.println("				<tr>");
out.println("					<td>");
out.println("						<span class=\"custom-checkbox\">");
out.println("							<input type=\"checkbox\" id=\"checkbox5\" name=\"options[]\" value=\"1\">");
out.println("							<label for=\"checkbox5\"></label>");
out.println("						</span>");
out.println("					</td>");
out.println("                       <td>5</td>");
out.println("					<td>Employee 5</td>");
out.println("					<td>27-Oct-2022</td>");
out.println("					<td>Type 5</td>");
out.println("					<td>From Addr 5</td>");
out.println("					<td>12345</td>");
out.println("					<td>To Addr 5</td>");
out.println("					<td>67890</td>");
out.println("					<td>Customer 5</td>");
out.println("                       <td>");
out.println("                           <a href=\"#editOrderModal\" class=\"edit\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Edit\">&#xE254;</i></a>");
out.println("                           <a href=\"#deleteOrderModal\" class=\"delete\" data-toggle=\"modal\"><i class=\"material-icons\" data-toggle=\"tooltip\" title=\"Delete\">&#xE872;</i></a>");
out.println("                       </td>");
out.println("                   </tr> ");
out.println("               </tbody>");
out.println("           </table>");
out.println("		<div class=\"clearfix\">");
out.println("               <div class=\"hint-text\">Showing <b>5</b> out of <b>25</b> entries</div>");
out.println("               <ul class=\"pagination\">");
out.println("                   <li class=\"page-item disabled\"><a href=\"#\">Previous</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">1</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">2</a></li>");
out.println("                   <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">3</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">4</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">5</a></li>");
out.println("                   <li class=\"page-item\"><a href=\"#\" class=\"page-link\">Next</a></li>");
out.println("               </ul>");
out.println("           </div>");
out.println("       </div>");
out.println("   </div>");
out.println("<!-- Edit Modal HTML -->");
out.println("<div id=\"addOrderModal\" class=\"modal fade\">");
out.println("	<div class=\"modal-dialog\">");
out.println("		<div class=\"modal-content\">");
out.println("			<form>");
out.println("				<div class=\"modal-header\">						");
out.println("					<h4 class=\"modal-title\">Create New Order</h4>");
out.println("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>");
out.println("				</div>");
out.println("				<div class=\"modal-body\">					");
out.println("					<div class=\"form-group\">");
out.println("						<label for=\"employeeSelectCreate\">Select Employee</label>");
out.println("						<select class=\"form-control\" id=\"employeeSelectCreate\">");
out.println("							<option>Employee 1</option>");
out.println("							<option>Employee 2</option>");
out.println("							<option>Employee 3</option>");
out.println("							<option>Employee 4</option>");
out.println("							<option>Employee 5</option>");
out.println("						</select>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>Date</label>");
out.println("						<input type=\"date\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label for=\"typeSelectCreate\">Choose Type</label>");
out.println("						<select class=\"form-control\" id=\"typeSelectCreate\">");
out.println("							<option>Type 1</option>");
out.println("							<option>Type 2</option>");
out.println("							<option>Type 3</option>");
out.println("							<option>Type 4</option>");
out.println("							<option>Type 5</option>");
out.println("						</select>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>From Address</label>");
out.println("						<textarea type=\"text\" class=\"form-control\" required></textarea>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>From Pincode</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>To Address</label>");
out.println("						<textarea type=\"text\" class=\"form-control\" required></textarea>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>To Pincode</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label for=\"customerSelectCreate\">Select Customer</label>");
out.println("						<select class=\"form-control\" id=\"customerSelectCreate\">");
out.println("							<option>Customer 1</option>");
out.println("							<option>Customer 2</option>");
out.println("							<option>Customer 3</option>");
out.println("							<option>Customer 4</option>");
out.println("							<option>Customer 5</option>");
out.println("						</select>");
out.println("					</div>			");
out.println("				</div>");
out.println("				<div class=\"modal-footer\">");
out.println("					<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" value=\"Cancel\">");
out.println("					<input type=\"submit\" class=\"btn btn-success\" value=\"Add\">");
out.println("				</div>");
out.println("			</form>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("<!-- Edit Modal HTML -->");
out.println("<div id=\"editOrderModal\" class=\"modal fade\">");
out.println("	<div class=\"modal-dialog\">");
out.println("		<div class=\"modal-content\">");
out.println("			<form>");
out.println("				<div class=\"modal-header\">						");
out.println("					<h4 class=\"modal-title\">Create New Order</h4>");
out.println("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>");
out.println("				</div>");
out.println("				<div class=\"modal-body\">					");
out.println("					<div class=\"form-group\">");
out.println("						<label for=\"employeeSelectEdit\">Select Employee</label>");
out.println("						<select class=\"form-control\" id=\"employeeSelectEdit\">");
out.println("							<option>Employee 1</option>");
out.println("							<option>Employee 2</option>");
out.println("							<option>Employee 3</option>");
out.println("							<option>Employee 4</option>");
out.println("							<option>Employee 5</option>");
out.println("						</select>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>Date</label>");
out.println("						<input type=\"date\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label for=\"typeSelectEdit\">Choose Type</label>");
out.println("						<select class=\"form-control\" id=\"typeSelectEdit\">");
out.println("							<option>Type 1</option>");
out.println("							<option>Type 2</option>");
out.println("							<option>Type 3</option>");
out.println("							<option>Type 4</option>");
out.println("							<option>Type 5</option>");
out.println("						</select>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>From Address</label>");
out.println("						<textarea type=\"text\" class=\"form-control\" required></textarea>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>From Pincode</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>To Address</label>");
out.println("						<textarea type=\"text\" class=\"form-control\" required></textarea>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label>To Pincode</label>");
out.println("						<input type=\"text\" class=\"form-control\" required>");
out.println("					</div>");
out.println("					<div class=\"form-group\">");
out.println("						<label for=\"customerSelectEdit\">Select Customer</label>");
out.println("						<select class=\"form-control\" id=\"customerSelectEdit\">");
out.println("							<option>Customer 1</option>");
out.println("							<option>Customer 2</option>");
out.println("							<option>Customer 3</option>");
out.println("							<option>Customer 4</option>");
out.println("							<option>Customer 5</option>");
out.println("						</select>");
out.println("					</div>			");
out.println("				</div>");
out.println("				<div class=\"modal-footer\">");
out.println("					<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" value=\"Cancel\">");
out.println("					<input type=\"submit\" class=\"btn btn-info\" value=\"Save\">");
out.println("				</div>");
out.println("			</form>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("<!-- Delete Modal HTML -->");
out.println("<div id=\"deleteOrderModal\" class=\"modal fade\">");
out.println("	<div class=\"modal-dialog\">");
out.println("		<div class=\"modal-content\">");
out.println("			<form>");
out.println("				<div class=\"modal-header\">						");
out.println("					<h4 class=\"modal-title\">Delete Customer</h4>");
out.println("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>");
out.println("				</div>");
out.println("				<div class=\"modal-body\">					");
out.println("					<p>Are you sure you want to delete these Records?</p>");
out.println("					<p class=\"text-warning\"><small>This action cannot be undone.</small></p>");
out.println("				</div>");
out.println("				<div class=\"modal-footer\">");
out.println("					<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\" value=\"Cancel\">");
out.println("					<input type=\"submit\" class=\"btn btn-danger\" value=\"Delete\">");
out.println("				</div>");
out.println("			</form>");
out.println("		</div>");
out.println("	</div>");
out.println("</div>");
out.println("/body>");
out.println("/html>");
%>