<%
out.println("<!DOCTYPE html>");
out.println("html>");
out.println("<head>");
out.println("	<meta charset=\"ISO-8859-1\">");
out.println("	<title>Login and Registration form example</title>");
out.println("	<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/register.css\">");
out.println("</head>");
out.println(" ");
out.println("<body bgcolor=\"#E6E6FA\">");
out.println(" ");
out.println("	<form name=\"regi\" action=\"register1.jsp\" method=\"post\">");
out.println("		<h2>Registration</h2>");
out.println("		 ");
out.println("		<label  for=\"r3\" id=\"un\">Username :</label>");
out.println("		<input type=\"text\" name=\"uname\" id=\"r3\"><br/>");
out.println("		 ");
out.println("		<label  for=\"r4\" id=\"pwd\">Password :</label>");
out.println("		<input type=\"password\" name=\"pass\" id=\"r4\"><br/>");
out.println("		 ");
out.println("		<label  for=\"r5\" id=\"em\">Email :</label>");
out.println("		<input type=\"text\" name=\"email\" id=\"r5\"><br/>");
out.println("		 ");
out.println("		<label  for=\"r6\" id=\"mn\">Mobile No :</label>");
out.println("		<input type=\"text\" name=\"mno\" id=\"r6\"><br/>");
out.println("		 ");
out.println("		<label for=\"r8\" id=\"cy\">City:</label>");
out.println("		 ");
out.println("		<select name=\"ct\" id=\"r8\">");
out.println("			<option>Select</option>");
out.println("			<option>Pune</option>");
out.println("			<option>Mumbai</option>");
out.println("			<option>Raigad</option>");
out.println("			<option>Nagpur</option>");
out.println("			<option>Nasik</option>");
out.println("			<option>Raigad</option>");
out.println("			<option>Nagar</option>");
out.println("			<option>Kolhapur</option>");
out.println("			<option>Solapur</option>");
out.println("		</select><br/><br/>");
out.println("		 ");
out.println("		<button type=\"submit\" value=\"Submit\" id=\"button\">Register</button>");
out.println("		<a href=\"login.html\">Login</a>");
out.println("	 ");
out.println("	</form>");
out.println(" ");
out.println("</body>");
out.println("/html>");
%>